name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_Linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Solver
        run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build -DCPACK_GENERATOR="TGZ"

      - name: Build Solver
        run: cmake --build ${{github.workspace}}/solver_application/build --target package

      - name: Make Solver Package
        run: cd _build && cpack -G "DEB" &&
             cpack -G "RPM" &&
             mkdir ../artifacts &&
             mv *.tar.gz ../artifacts/ &&
             mv *.deb ../artifacts/ &&
             mv *.rpm ../artifacts/

  build_Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Solver
        run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build -DCPACK_GENERATOR="ZIP"

      - name: Build Solver
        run: cmake --build ${{github.workspace}}/solver_application/build

      - name: Make Solver Package
        run: cd _build && cpack -G "DEB" &&
             cpack -G "RPM" &&
             mkdir ../artifacts &&
             mv *.tar.gz ../artifacts/ &&
             mv *.deb ../artifacts/ &&
             mv *.rpm ../artifacts/

      